// ═══════════════════════════════════════════════════════════════
// API Route — GET /api/setup (detect gateway) | POST /api/setup (save config)
// Auto-detects OpenClaw binary, workspace, and gateway RPC URL.
// POST is only allowed when DASHBOARD_SECRET is not yet set
// (i.e., first-time setup). After setup, this endpoint is locked.
// ═══════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";
import { writeFile, mkdir, access } from "fs/promises";
import { execFile as execFileCb } from "child_process";
import { promisify } from "util";
import { randomBytes } from "crypto";
import { join } from "path";
import { homedir } from "os";

const execFile = promisify(execFileCb);

const CONFIG_DIR = join(homedir(), ".config", "openclaw-mission-control");
const CONFIG_FILE = join(CONFIG_DIR, ".env.local");
const ORG_NAME_PATTERN = /^[a-zA-Z0-9\s&.,'-]+$/;

// ── Auto-detection helpers ──────────────────────────────────

async function detectBinary(): Promise<string | null> {
  try {
    const { stdout } = await execFile("which", ["openclaw"], { timeout: 3000 });
    return stdout.trim() || null;
  } catch {
    return null;
  }
}

async function detectWorkspace(): Promise<string | null> {
  const candidates = [
    join(homedir(), ".openclaw", "agents", "main", "workspace"),
    join(homedir(), ".openclaw", "workspace"),
    join(homedir(), ".openclaw"),
  ];
  for (const p of candidates) {
    try {
      await access(p);
      return p;
    } catch {
      continue;
    }
  }
  return null;
}

interface GatewayDetection {
  running: boolean;
  rpcUrl: string | null;
  port: number | null;
}

async function detectGateway(bin: string): Promise<GatewayDetection> {
  try {
    const { stdout } = await execFile(bin, ["gateway", "status", "--json"], {
      timeout: 5000,
    });
    const data = JSON.parse(stdout);
    const rt = data.service?.runtime || data.runtime;
    const isRunning = rt?.status === "running" || rt?.state === "active";
    const rpcUrl = data.rpc?.url || data.gateway?.probeUrl || null;
    const port = data.gateway?.port || null;
    return { running: isRunning, rpcUrl, port };
  } catch {
    return { running: false, rpcUrl: null, port: null };
  }
}

// ── GET — detect gateway ────────────────────────────────────

export async function GET(): Promise<NextResponse> {
  const binary = await detectBinary();
  const workspace = await detectWorkspace();
  const gateway = binary ? await detectGateway(binary) : { running: false, rpcUrl: null, port: null };

  return NextResponse.json({
    binary,
    workspace,
    gateway: gateway.running ? {
      running: true,
      rpcUrl: gateway.rpcUrl,
      port: gateway.port,
    } : { running: false },
    gatewayReachable: gateway.running,
  });
}

// ── POST — save config (first-time only) ────────────────────

interface SetupBody {
  orgName: string;
}

export async function POST(
  request: NextRequest
): Promise<NextResponse> {
  try {
    // Block setup if already configured (secret exists)
    if (process.env.DASHBOARD_SECRET) {
      return NextResponse.json(
        { error: "Setup already complete. Reconfigure via CLI." },
        { status: 403 }
      );
    }

    let body: SetupBody;

    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: "Invalid JSON body" },
        { status: 400 }
      );
    }

    const { orgName } = body;

    if (
      !orgName ||
      typeof orgName !== "string" ||
      orgName.trim().length < 2 ||
      orgName.trim().length > 50 ||
      !ORG_NAME_PATTERN.test(orgName.trim())
    ) {
      return NextResponse.json(
        { error: "Invalid organization name. Use 2-50 alphanumeric characters." },
        { status: 400 }
      );
    }

    const sanitized = orgName.trim();

    // Auto-detect gateway configuration
    const binary = await detectBinary();
    const workspace = await detectWorkspace();
    const gateway = binary ? await detectGateway(binary) : { running: false, rpcUrl: null, port: null };

    // Generate dashboard secret for auth
    const dashboardSecret = randomBytes(32).toString("hex");

    // Preserve already-exported gateway auth env (if present)
    const gatewayToken = process.env.OPENCLAW_GATEWAY_TOKEN || "";
    const gatewayPassword = process.env.OPENCLAW_GATEWAY_PASSWORD || "";

    // Build .env.local content with detected values
    const envContent = [
      `# OpenClaw Mission Control Configuration`,
      `# Generated by setup wizard on ${new Date().toISOString()}`,
      ``,
      `ORG_NAME="${sanitized}"`,
      `DASHBOARD_SECRET=${dashboardSecret}`,
      `OPENCLAW_BIN=${binary || "openclaw"}`,
      `WORKSPACE_PATH=${workspace || ""}`,
      `OPENCLAW_GATEWAY_URL=${gateway.rpcUrl || ""}`,
      `OPENCLAW_GATEWAY_TOKEN=${gatewayToken}`,
      `OPENCLAW_GATEWAY_PASSWORD=${gatewayPassword}`,
      `PORT=3000`,
      ``,
    ].join("\n");

    // Ensure config directory exists
    await mkdir(CONFIG_DIR, { recursive: true });

    // Write config file
    await writeFile(CONFIG_FILE, envContent, { mode: 0o600 });

    // Set session cookie so the user is authenticated after restart
    const response = NextResponse.json({
      success: true,
      message: "Configuration saved",
      configPath: CONFIG_FILE,
      detected: {
        binary: !!binary,
        workspace: !!workspace,
        gateway: gateway.running,
      },
    });

    // Set the session cookie with the new secret
    response.cookies.set("mc_session", dashboardSecret, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict",
      path: "/",
      maxAge: 60 * 60 * 24 * 30,
    });

    return response;
  } catch {
    return NextResponse.json(
      { error: "Failed to save configuration" },
      { status: 500 }
    );
  }
}
